<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="TerraLinux" ignored="0" name="Retry Test" tests="4" failures="1" timestamp="09 Apr 2019 10:35:35 GMT" time="0.095" errors="0">
  <testcase name="doLogin" time="0.019" classname="Retry.TestLogin"/>
  <testcase name="doRegistration" time="0.007" classname="Retry.TestLogin">
    <skipped/>
  </testcase> <!-- doRegistration -->
  <testcase name="doRegistration" time="0.003" classname="Retry.TestLogin">
    <skipped/>
  </testcase> <!-- doRegistration -->
  <testcase name="doRegistration" time="0.015" classname="Retry.TestLogin">
    <failure type="java.lang.AssertionError" message="expected [4] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [3]
at Retry.TestLogin.doRegistration(TestLogin.java:18)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- doRegistration -->
</testsuite> <!-- Retry Test -->
